/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.salesmanRole;
import business.EcoSystem;
import business.building.BuildingDirectory;
import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDirectory;
import business.network.Network;
import business.organization.AgentSalesmanOrganization;
import business.useraccount.UserAccount;
import business.workqueue.LabTestWorkRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */
public class AgentSalesmanRoleJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AgentSalesmanRoleJpanel
     */
    private JPanel userProcessContainer;
    private AgentSalesmanOrganization ASOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    
    public AgentSalesmanRoleJpanel(JPanel userProcessContainer, UserAccount account, AgentSalesmanOrganization ASOrganization,Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.ASOrganization = (AgentSalesmanOrganization)ASOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manageapartmentsJBtn = new javax.swing.JButton();
        MCRJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enterprise: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salesman");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        manageapartmentsJBtn.setText("Manage Apartments");
        manageapartmentsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageapartmentsJBtnActionPerformed(evt);
            }
        });
        add(manageapartmentsJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 97, 230, -1));

        MCRJBtn.setText("Manage Customers' Requests");
        MCRJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCRJBtnActionPerformed(evt);
            }
        });
        add(MCRJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 179, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageapartmentsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageapartmentsJBtnActionPerformed
        // TODO add your handling code here:
        ASManageApartmentsJpanel manageApartmentsJpanel = new ASManageApartmentsJpanel(userProcessContainer, userAccount);
        userProcessContainer.add("manageApartmentsJpanel", manageApartmentsJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageapartmentsJBtnActionPerformed

    private void MCRJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCRJBtnActionPerformed
        // TODO add your handling code here:
        ASRequestfromCustomerJpanel requestfromCustomerJpanel = new ASRequestfromCustomerJpanel(userProcessContainer, userAccount);
        userProcessContainer.add("requestfromCustomerJpanel",requestfromCustomerJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MCRJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MCRJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageapartmentsJBtn;
    // End of variables declaration//GEN-END:variables
}
