/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.salesmanRole;

/**
 *
 * @author apple
 */
import business.building.Apartment;
import business.building.Building;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import business.building.BuildingDirectory;
import business.employee.Employee;
import business.enterprise.Enterprise;
import business.role.Role;
import business.useraccount.UserAccount;
import business.workqueue.ManagerSalesmanRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
public class EditAptInformationJpanel extends javax.swing.JPanel {
    private Apartment apt;
    private JPanel userProcessContainer;
    /**
     * Creates new form EditAptInformationJpanel
     */
    public EditAptInformationJpanel(JPanel userProcessContainer, Apartment apt) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.apt= apt;
//        txtAptID.setEnabled(false);
        
        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAptPrice = new javax.swing.JTextField();
        txtAptBed = new javax.swing.JTextField();
        txtAptBath = new javax.swing.JTextField();
        BackJBtn = new javax.swing.JButton();
        SubmitJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Apartment Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 23, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bath:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bed:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 174, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 218, -1, -1));
        add(txtAptPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 213, 200, -1));
        add(txtAptBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 169, 200, -1));

        txtAptBath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAptBathActionPerformed(evt);
            }
        });
        add(txtAptBath, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 125, 200, -1));

        BackJBtn.setText("<<BACK");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 286, -1, -1));

        SubmitJBtn.setText("Submit");
        SubmitJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitJBtnActionPerformed(evt);
            }
        });
        add(SubmitJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 286, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAptBathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAptBathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAptBathActionPerformed

    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)this.userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJBtnActionPerformed

    private void SubmitJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitJBtnActionPerformed
        // TODO add your handling code here:
        if(txtAptBath.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Apartment's Bath cannot be empty");
            return;
        }
              if(txtAptBed.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Apartment's Bed cannot be empty");
            return;
        }
              if(txtAptPrice.getText().isEmpty()){
                  JOptionPane.showMessageDialog(null, "Price cannot be empty");
            return;
              }
           else try{
            int avaNum =Integer.parseInt(txtAptPrice.getText());
            int avaBed = Integer.parseInt(txtAptBed.getText());
            int avaBath = Integer.parseInt(txtAptBath.getText());
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "It only allows number ");
            return;
        }
        
            apt.setBath(Integer.parseInt(txtAptBath.getText()));
            apt.setBed(Integer.parseInt(txtAptBed.getText()));
            apt.setPrice(Long.parseLong(txtAptPrice.getText()));
        
               
            
            
            
        
        
        JOptionPane.showMessageDialog(null,"Apartment has been created succesfully!");
    }//GEN-LAST:event_SubmitJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JButton SubmitJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAptBath;
    private javax.swing.JTextField txtAptBed;
    private javax.swing.JTextField txtAptPrice;
    // End of variables declaration//GEN-END:variables
}
