/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managerRole;
import business.EcoSystem;
import business.building.Building;
import business.building.BuildingDirectory;
import business.enterprise.Enterprise;
import business.enterprise.EnterpriseDirectory;
import business.network.Network;
import business.organization.AgentManagerOrganization;
import business.useraccount.UserAccount;
import business.workqueue.LabTestWorkRequest;
import business.workqueue.ManagerManagerRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author apple
 */
public class AgentManagerRoleJpanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private AgentManagerOrganization organization;
    //private Building building;
    private BuildingDirectory buildingdir;
    /**
     * Creates new form AgentManagerRoleJpanel
     */
    public AgentManagerRoleJpanel(JPanel userProcessContainer, UserAccount account, AgentManagerOrganization organization,Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.buildingdir = enterprise.getBuildingDirectory();
        //buildingdir = new BuildingDirectory();
        populateTable();
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            if(request.getReceiver()==null){
                Object[] row = new Object[model.getColumnCount()];
                Building building = ((ManagerManagerRequest) request).getBuilding();
                
                row[0] = building;
                row[1] = request.getSender().getEmployee().getName();
                row[2] = request;
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                

                model.addRow(row);
            }
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        refreshTestJButton = new javax.swing.JButton();
        assignJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        SelectAptJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 20, 127, 30));

        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("Agent Manager");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 24, 158, 26));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 21, -1, -1));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 249, -1, -1));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Address", "Sender", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 68, 523, 163));

        SelectAptJBtn.setText("Select Apartment");
        SelectAptJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectAptJBtnActionPerformed(evt);
            }
        });
        add(SelectAptJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 249, 134, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {
            ManagerManagerRequest request = (ManagerManagerRequest) workRequestJTable.getValueAt(selectedRow, 2);
            if(request.getReceiver() == null){
                request.setReceiver(userAccount);
                request.setResult("Accepted");
                request.setStatus("Finished");
                enterprise.getBuildingDirectory().getBuildinglist().add(request.getBuilding());
                populateTable();
                JOptionPane.showMessageDialog(null, "Successfully Accepted.");                
                //buildingdir.getBuildinglist().add(request.getBuilding());
            }
            else if(request.getReceiver().equals(userAccount)){
                JOptionPane.showMessageDialog(null, "You have accepted this one.");            
            }
            else{
                JOptionPane.showMessageDialog(null, "Others have accepted this one.");
            }
            /*if (request.getMessage().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } else {
                request.setReceiver(userAccount);
                request.setStatus("Pending");
                populateTable();

            }*/

        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
            return;
        }
    }//GEN-LAST:event_assignJButtonActionPerformed

    private void SelectAptJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectAptJBtnActionPerformed
        // TODO add your handling code here:
        //BuildingDirectory buildingdirectory = enterprise.getBuildingDirectory();
        //EnterpriseDirectory enterprisedirectory = network.getEnterpriseDirectory();
        
        SelectAptJpanel selectAptJpanel = new SelectAptJpanel(userProcessContainer, enterprise, buildingdir, userAccount);
        userProcessContainer.add("sendtoSalesmanJpanel", selectAptJpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_SelectAptJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectAptJBtn;
    private javax.swing.JButton assignJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
