/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managerRole;

import business.building.Apartment;
import business.building.Building;
import business.building.BuildingDirectory;
import business.enterprise.Enterprise;
import business.organization.AgentManagerOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haowenchang
 */
public class SelectAptJpanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectAptJpanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    private BuildingDirectory buildingdir;
    private UserAccount userAccount;
    public SelectAptJpanel(JPanel userProcessContainer, Enterprise enterprise, BuildingDirectory buildingdir,UserAccount useraccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        
        this.buildingdir = buildingdir;
        this.userAccount = useraccount;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackJBtn = new javax.swing.JButton();
        Selectsalesman = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbApts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackJBtn.setText("<<<Back");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 283, -1, -1));

        Selectsalesman.setText("Select Salesman");
        Selectsalesman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectsalesmanActionPerformed(evt);
            }
        });
        add(Selectsalesman, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 283, 128, -1));

        tbApts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Room Number", "Level", "Num of room", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbApts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 62, 591, 187));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select an Apartment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbApts.getModel();

        model.setRowCount(0);
        for(Building building : buildingdir.getBuildinglist()){                    
            for(Apartment apt : building.getApartmentlist()){
                //System.out.print(apt.getSalesman());
                if(apt.getSalesman()==null){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = apt;
                    
                    row[1] = apt.getLel();
                    row[2] = apt.getNum();
                    row[3] = building;
                    model.addRow(row);
                }
            }
        }

    }
    
    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackJBtnActionPerformed

    
    private void SelectsalesmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectsalesmanActionPerformed
        // TODO add your handling code here:

        int selectedrow=tbApts.getSelectedRow();

        if(selectedrow>=0){
            //Building building = (Building)tbBuildings.getValueAt(selectedrow, 0);
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure this Apartment??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Building building = (Building)tbApts.getValueAt(selectedrow, 3);
                Apartment apt = (Apartment)tbApts.getValueAt(selectedrow, 0);

                SendtoSalesmanJpanel sendtoSalesmanJpanel = new SendtoSalesmanJpanel(userProcessContainer, building, apt, enterprise, userAccount);
                userProcessContainer.add("sendtoSalesmanJpanel", sendtoSalesmanJpanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            
        }
        else
            JOptionPane.showMessageDialog(null,"Please select any row");
    }//GEN-LAST:event_SelectsalesmanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JButton Selectsalesman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbApts;
    // End of variables declaration//GEN-END:variables
}
