/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.managerRole;

import business.building.Building;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import business.workqueue.ManagerManagerRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haowenchang
 */
public class SelectManageJpanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectManageJpanel
     */
    private JPanel userProcessContainer;
    private Building building;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public SelectManageJpanel(JPanel userProcessContainer,Building building, Enterprise enterprise, UserAccount useraccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.building = building;
        this.enterprise = enterprise;
        this.userAccount = useraccount;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbManager = new javax.swing.JTable();
        BackJBtn = new javax.swing.JButton();
        SendJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Account"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbManager);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 552, 211));

        BackJBtn.setText("<<<Back");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 298, -1, -1));

        SendJBtn.setText("Send Request");
        SendJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendJBtnActionPerformed(evt);
            }
        });
        add(SendJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 298, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable(){
        DefaultTableModel dtm=(DefaultTableModel)tbManager.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList()){
            for(UserAccount useraccount : organization.getUserAccountDirectory().getUserAccountList()){
                //System.out.println(String.valueOf(useraccount.getRole()));
                if(String.valueOf(useraccount.getRole()).contains("AgentManager")){
                    Object row[]= new Object[dtm.getColumnCount()];
                    row[0] = useraccount.getEmployee().getId();
                    row[1] = useraccount.getEmployee().getName();
                    row[2] = useraccount;
                    dtm.addRow(row);
                }
            }
            
        }
    }
    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //backAction();
    }//GEN-LAST:event_BackJBtnActionPerformed

    private void SendJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendJBtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = tbManager.getSelectedRow();
        if(selectedrow>=0){
            //Building building = (Building)tbBuildings.getValueAt(selectedrow, 0);
            UserAccount receiver = (UserAccount)tbManager.getValueAt(selectedrow, 2);
            ManagerManagerRequest request = new ManagerManagerRequest();
            request.setBuilding(building);
            request.setSender(userAccount);
            request.setReceiver(receiver);
            request.setStatus("Sent");
            userAccount.getWorkqueue().getWorkRequestList().add(request);
            receiver.getWorkqueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request message sent");
        }
        else
        JOptionPane.showMessageDialog(null,"Please select any row");
    }//GEN-LAST:event_SendJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JButton SendJBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbManager;
    // End of variables declaration//GEN-END:variables
}
