/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.administrativeRole;


import business.EcoSystem;
import business.building.Building;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import business.building.BuildingDirectory;
import business.employee.Employee;
import business.enterprise.Enterprise;
import business.network.Network;
import business.role.Role;
import business.useraccount.UserAccount;
import com.db4o.instrumentation.file.FilePathRoot;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author apple
 */

public class AddBuildingsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AddBuildingsJpanel
     */
    private BuildingDirectory buildingDir;
    private JPanel userProcessContainer;
    private EcoSystem system;
    private String pic;
    public AddBuildingsJpanel(JPanel userProcessContainer, BuildingDirectory buildingDir, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.buildingDir = buildingDir;
        this.system = system;
        this.pic=pic;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubJBtn = new javax.swing.JButton();
        BackJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextCost = new javax.swing.JTextField();
        TextAddress = new javax.swing.JTextField();
        TextName = new javax.swing.JTextField();
        TextLevel = new javax.swing.JTextField();
        TextNumApt = new javax.swing.JTextField();
        UploadJBtn = new javax.swing.JButton();
        Showpic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(166, 166, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubJBtn.setText("Submit");
        SubJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubJBtnActionPerformed(evt);
            }
        });
        add(SubJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        BackJBtn.setText("<<<Back");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Building Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 95, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cost:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 139, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Picture:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 183, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Level:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 259, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of apartments in Every Level:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 303, -1, -1));
        add(TextCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 134, 98, -1));
        add(TextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 90, 98, -1));
        add(TextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 215, 100, -1));
        add(TextLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 259, 100, -1));
        add(TextNumApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 303, 100, -1));

        UploadJBtn.setText("Upload");
        UploadJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadJBtnActionPerformed(evt);
            }
        });
        add(UploadJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 178, -1, -1));

        Showpic.setBackground(new java.awt.Color(255, 255, 255));
        Showpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(Showpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 76, 220, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void UploadJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadJBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fd = new JFileChooser();
        fd.showOpenDialog(null);        
        File f = fd.getSelectedFile();
        
        String filepathString = f.getAbsolutePath();
        pic = filepathString;
 
        if(filepathString !=null){
            ImageIcon icon = new ImageIcon(filepathString);
            icon.setImage(icon.getImage().getScaledInstance(220,230,Image.SCALE_DEFAULT));
            Showpic.setIcon(icon);
        }       
        
    }//GEN-LAST:event_UploadJBtnActionPerformed

    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        /*userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);*/
        backAction();
        
    }//GEN-LAST:event_BackJBtnActionPerformed

    private void backAction() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageBuildingsJpanel mbj = (ManageBuildingsJpanel) component;
        mbj.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    private void SubJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubJBtnActionPerformed
        // TODO add your handling code here:
        if(TextAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Building's Address cannot be empty");
            return;
        }
           else if(TextCost.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Building's cost cannot be empty");
            return;
        }
        else if(TextName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Building's name cannot be empty");
            return;
        }
        else if(TextLevel.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Building's level cannot be empty");
            return;
        }
        else if(TextNumApt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Building's number of apartments cannot be empty");
            return;
        }
            
        else try{
            int avaNum =Integer.parseInt(TextCost.getText());
            int avaLevel = Integer.parseInt(TextLevel.getText());
            int avaNumApt = Integer.parseInt(TextNumApt.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Only allows number ");
            return;
        }
        
        Boolean exist = false;
        for(Network network:system.getNetworkList()){
        for(Enterprise enter: network.getEnterpriseDirectory().getEnterpriseList()){
            for(Building build: enter.getBuildingDirectory().getBuildinglist()){
                if(build.getAddress().equals(TextAddress.getText())){
                    JOptionPane.showMessageDialog(null,"Has a building here!");
                    exist = true;
                    return;
                }                
            }
        }
        }
        if(!exist){
            Building building=buildingDir.createbuilding(TextAddress.getText(),Integer.parseInt(TextLevel.getText()),Integer.parseInt(TextNumApt.getText()));     
            building.setAddress(TextAddress.getText());
            building.setPic(pic);
            building.setCost(Long.parseLong(TextCost.getText()));
            building.setName(TextName.getText());
            building.setLevel(Integer.parseInt(TextLevel.getText()));
            building.setNpl(Integer.parseInt(TextNumApt.getText()));
            JOptionPane.showMessageDialog(null,"Building has been created succesfully!");
        }
    }//GEN-LAST:event_SubJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JLabel Showpic;
    private javax.swing.JButton SubJBtn;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextField TextCost;
    private javax.swing.JTextField TextLevel;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextNumApt;
    private javax.swing.JButton UploadJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
